### ISSUE TITLE
airspy graphs in tar1090 container

### ISSUE THREAD

**Issue by rikgale** [sdr-enthusiasts/airspy_adsb#4]
On a baremetal install of [wiedehopf](https://github.com/wiedehopf)/[airspy-conf](https://github.com/wiedehopf/airspy-conf) the airspy info is shown in the graphs of the tar1090 container, but they do not appear to work when I am using this container.

How do I get these graphs to work?

I have posted both composes incase I am missing something obvious.

![image](https://user-images.githubusercontent.com/66202012/228066423-657037d8-6a05-4c41-94b5-999500280a71.png)

```
  tar1090:
    image: ghcr.io/sdr-enthusiasts/docker-tar1090:latest
    tty: true
    container_name: tar1090
    restart: always
    privileged: true
    environment:
      - UPDATE_TAR1090=true
      - TZ=${FEEDER_TZ}
      - BEASTHOST=readsb
      - MLATHOST=mlathub
      - LAT=${FEEDER_LAT}
      - LONG=${FEEDER_LONG}
      - TAR1090_DEFAULTCENTERLAT=${FEEDER_LAT}
      - TAR1090_DEFAULTCENTERLON=${FEEDER_LONG}
      - GRAPHS1090_DARKMODE=true
      - ENABLE_AIRSPY=yes
    ports:
      - 8082:80
    volumes:
      - /opt/adsb/tar1090/globe_history:/var/globe_history
      - /opt/adsb/tar1090/timelapse1090:/var/timelapse1090
      - /opt/adsb/tar1090/graphs1090:/var/lib/collectd
      - /run/airspy_adsb:/run/airspy_adsb
    tmpfs:
      - /run:exec,size=64M
      - /var/log
```

```  
  airspy_adsb:
    image: ghcr.io/sdr-enthusiasts/airspy_adsb:latest
    tty: true
    container_name: airspy_adsb
    hostname: airspy_adsb
    restart: always
    devices:
      - /dev/bus/usb:/dev/bus/usb
    environment:
      - AIRSPY_ADSB_VERBOSE=true
      - AIRSPY_ADSB_TIMEOUT=90
      - AIRSPY_ADSB_FEC_BITS=1
      - AIRSPY_ADSB_WHITELIST_THRESHOLD=5
      - AIRSPY_ADSB_PREAMBLE_FILTER_NONCRC=8
      - AIRSPY_ADSB_CPUTIME_TARGET=60
      - AIRSPY_ADSB_PREAMBLE_FILTER_MAX=20
      - AIRSPY_ADSB_MLAT_FREQ=12
      - AIRSPY_ADSB_RF_GAIN=auto
      - AIRSPY_ADSB_BIAS_TEE=true
```
